config/routes.rb
Rails.application.routes.draw do

  get 'categories/index'

  get 'categories/index'

  root to: 'cards#index'

  resources :cards, only: [:index, :show]
  resources :categories, only: [:index, :show]
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :category

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :cards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def index
    @cards = Card.all
  end

  def show
    @card = Card.find(params[:id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @cards = @category.cards
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/cards/index.html.erb
<h1>Cards</h1>

<div class="row">
  <% @cards.each do |card| %>
  <div class="col s12 m5">
    <div class="card medium">
      <span class="card-title black-text"><%= card.name %></span>
      <div class="card-image">
        <%= image_tag card.image, :size => "200x200" %><br>
      </div>
      <div class="card-content">
        <p><%= card.message %></p>
      </div>
      <div class="card-action">
        <%= link_to "View Card", card_path(card.id) %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/cards/show.html.erb
<h2><%= @card.name %></h2>

<%= image_tag @card.image, :size => "200x200" %><br>
<%= @card.message %>

app/views/categories/index.html.erb
<h1 class="center">Categories</h1>

<div class="container">
  <div class="center-align">
    <div style="overflow: scrollbars-none;">
      <div style="overflow:scroll; height:600px;">
        <div class="categories">
          <% @categories.each do |category| %>
          <div class="row center-align">
            <div class="col s12 offset-4">
              <div class="card grey darken-2 location-card">
                <div class="card-content white-text bold">
                  <span class="card-title"><%= link_to "#{category.name.titleize}", category_path(category), class:"text-cyan text-accent-4 krista" %></span>
                </div>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<h2> <%= @category.name.titleize %></h2>


<div class="row">
  <% @cards.each do |card| %>
  <div class="col s12 m5">
    <div class="card medium">
      <span class="card-title black-text"><%= card.name %></span>
      <div class="card-image">
        <%= image_tag card.image, :size => "100x300" %><br>
      </div>
      <div class="card-content">
        <p><%= card.message %></p>
      </div>
      <div class="card-action">
        <%= link_to "View Card", card_path(card.id) %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NiceApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "partials/nav" %>

<%= yield %>

</body>
</html>

app/views/partials/_nav.html.erb
<div class="navbar-fixed">
  <nav>
    <div class="nav-wrapper">
      <a href="/" class="brand-logo">Cards and Stuff</a>
      <ul class="right hide-on-med-and-down">
        <li class="active"><a href="/categories">Categories</a></li>
        <li class="active"><a href="/">Home</a></li>
      </ul>
    </div>
  </nav>
</div>